---
- name: check backup file exists
  stat:
    path: "{{ nginx_config_file }}.backup"
  register: nginx_backup_stat_result

- name: remove symlink
  become: yes
  file:
    path: "{{ nginx_config_file }}"
    state: absent

- name: rename old nginx.conf for backup
  become: yes
  command: "mv {{ nginx_config_file }} {{ nginx_config_file }}.backup"
  when: not nginx_backup_stat_result.stat.exists

- name: locate nginx.conf
  become: yes
  template:
    src: nginx.conf
    dest: "{{ isucon_config_dir }}nginx.conf"
    mode: 0644
    owner: "{{ isucon_user }}"
    group: "{{ isucon_group }}"
    force: yes
  when: nginx_backup_stat_result.stat.exists

- name: create symlink
  become: yes
  file:
    src: "{{ isucon_config_dir }}nginx.conf"
    dest: "{{ nginx_config_file }}"
    state: hard
    owner: root
    group: root
    mode: 0644
    force: yes

- name: restart nginx
  become: yes
  service: name=nginx state=restarted
