---
- name: add nginx log conf
  template:
    src: log_format.conf
    dest: /etc/nginx/conf.d/log.conf

- name: download alp
  get_url:
    url: https://github.com/tkuchiki/alp/releases/download/v0.3.1/alp_linux_amd64.zip
    dest: /tmp/alp_linux_amd64.zip

- name: unzip alp
  unarchive:
    src: /tmp/alp_linux_amd64.zip
    dest: /usr/local/bin/

- name: chown root:root
  become: yes
  file:
    path: /usr/local/bin/alp
    group: root
    owner: root
