---
- name: check mysql exists
  stat:
    path: /etc/mysql/my.cnf
  register: mysql_stat_result

- name: backup my.cnf
  copy:
    src: /etc/mysql/my.cnf
    dest: /etc/mysql/my.cnf.backup
    mode: 0644
    backup: yes
  when: mysql_stat_result.stat.exists == True

- name: replace my.cnf
  template:
    src: my.cnf
    dest: /etc/mysql/my.cnf
  when: mysql_stat_result.stat.exists == True

- name: restart mysql
  service: name=mysql state=restarted enabled=yes
  when: mysql_stat_result.stat.exists == True
