---
- name: check mysql exists
  stat:
    path: "{{ mysql_config_file }}"
  register: mysql_stat_result

- name: check backup file exists
  stat:
    path: "{{ mysql_config_file }}.backup"
  register: mysql_backup_stat_result

- name: remove symlink
  become: yes
  file:
    path: "{{ mysql_config_file }}"
    state: absent

- name: rename old my.cnf for backup
  become: yes
  command: "mv {{ mysql_config_file }} {{ mysql_config_file }}.backup"
  when: mysql_stat_result.stat.exists and not mysql_backup_stat_result.stat.exists

- name: locate my.cnf
  become: yes
  template:
    src: my.cnf
    dest: "{{ isucon_config_dir }}mysql.cnf"
    mode: 0644
    owner: "{{ isucon_user }}"
    group: "{{ isucon_group }}"
    force: yes
  when: mysql_stat_result.stat.exists

- name: create symlink
  become: yes
  file:
    src: "{{ isucon_config_dir }}mysql.cnf"
    dest: "{{ mysql_config_file }}"
    state: hard
    owner: root
    group: root
    mode: 0644
    force: yes

- name: restart mysql
  become: yes
  service: name=mysql state=restarted enabled=yes
  when: mysql_stat_result.stat.exists
