---
- name: check mysql exists
  stat:
    path: "{{ mysql_config_file }}"
  register: mysql_stat_result

- name: create symlink
  file:
    src: "{{ mysql_config_file }}"
    dest: "{{ isucon_config_dir }}/mysql.cnf"
    state: hard

- name: backup my.cnf
  copy:
    src: "{{ mysql_config_file }}"
    dest: "{{ mysql_config_dir }}"
    mode: 0644
    backup: yes
  when: mysql_stat_result.stat.exists == True

- name: replace my.cnf
  template:
    src: my.cnf
    dest: "{{ mysql_config_file }}"
  when: mysql_stat_result.stat.exists == True

- name: restart mysql
  service: name=mysql state=restarted enabled=yes
  when: mysql_stat_result.stat.exists == True
