---
- name: check mysql exists
  stat:
    path: "{{ mysql_config_file }}"
  register: mysql_stat_result

- name: backup my.cnf
  become: yes
  copy:
    src: "{{ mysql_config_file }}"
    dest: "{{ mysql_config_dir }}"
    mode: 0644
    backup: yes
  when: mysql_stat_result.stat.exists == True

- name: remove symlink
  become: yes
  file:
    path: "{{ isucon_config_dir }}mysql.cnf"
    state: absent

- name: replace my.cnf
  become: yes
  template:
    src: my.cnf
    dest: "{{ mysql_config_file }}"
    mode: 0644
  when: mysql_stat_result.stat.exists == True

- name: restart mysql
  become: yes
  service: name=mysql state=restarted enabled=yes
  when: mysql_stat_result.stat.exists == True

- name: create symlink
  become: yes
  file:
    src: "{{ mysql_config_file }}"
    dest: "{{ isucon_config_dir }}mysql.cnf"
    state: hard
    owner: "{{ isucon_user }}"
    group: "{{ isucon_group }}"
    mode: 0644
    force: yes
