---
- sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 2000000
    reload: yes

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: "10000 65000"
    reload: yes

- sysctl:
    name: net.core.somaxconn
    value: 32768
    reload: yes

- sysctl:
    name: net.core.netdev_max_backlog
    value: 8192
    reload: yes

- sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    reload: yes

- sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 10
    reload: yes
