---
- name: install unzip
  become: yes
  action: "{{ ansible_pkg_mgr }} name=unzip state=present"

- name: make directory for isucon configs
  become: yes
  file:
    path: "{{ isucon_config_dir }}"
    state: directory
    owner: 'isucon'
    group: 'isucon'
    mode: '755'
