---
- name: install unzip
  action: "{{ ansible_pkg_mgr }} name=unzip state=present"

- name: make directory for isucon configs
  file:
    path: "{{ isucon_config_dir }}"
    state: directory
    owner: "{{ isucon_user }}"
    group: "{{ isucon_group }}"
    mode: 0644
