---
- name: create benchmark directory
  file:
    path: "{{ ansible_env.PWD }}/../benchmark"
    state: directory
    owner: root
    group: root
    mode: 075

- name: add benchmark scripts
  template: 
    src: "{{ item }}"
    dest: "{{ ansible_env.PWD }}/../benchmark"
  with_items:
    - alp.sh
